# Generated by Django 2.0.2 on 2020-01-09 17:43

from django.db import migrations

def forward (apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.all().only('id', 'telephone').iterator():
        student.telephone = ' '.join(x for x in student.telephone if x.isdigit())
        student.save(update_fields=['telephone'])


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_address'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
